name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [published]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
    - name: Run tests
      run: sbt test
    - name: Run jlink
      run: sbt universal:packageZipTarball
    - uses: actions/upload-artifact@v3
      with:
        name: Click Em All
        path: |
          target/universal/scala-bricks-*.tgz
    - name: Upload release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: target/universal/scala-bricks-1.0.0.tgz
        asset_name: bricks-x86_64-pc-linux.tgz
        asset_content_type: application/zip

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
    - name: Run tests
      run: sbt test
    - name: Run jlink
      run: sbt windows:packageBin
    - name: Search msi file
      run: dir /s *msi*
    - uses: actions/upload-artifact@v3
      with:
        name: Click Em All
        path: |
          target/scala-bricks-*.msi
    - name: Upload release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: target/scala-bricks-1.0.0.msi
        asset_name: bricks-x86_64-pc-windows.msi
        asset_content_type: application/zip

  build-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
    - name: Run tests
      run: sbt test
    - name: Run jlink
      run: sbt universal:packageOsxDmg
    - uses: actions/upload-artifact@v3
      with:
        name: Click Em All
        path: |
          target/universal/scala-bricks-*.dmg
    - name: Upload release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: target/universal/scala-bricks-1.0.0.dmg
        asset_name: bricks-x86_64-apple-darwin.dmg
        asset_content_type: application/zip
